In [1]:
Print("hello")

NameError: name 'Print' is not defined

In [2]:
print("hello")


hello


In [3]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6


In [6]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr1", arr1.shape)
print("Size of arr2", arr2.size)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr1 (5,)
Size of arr2 6


In [7]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)


iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6


In [8]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#3. Array operations
print("Addition", arr1 + 5)
print("Multiplication", arr1 + 2)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Addition [15 25 35 45 55]
Multiplication [12 22 32 42 52]


In [9]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#Mathematical functions
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))
print("Min:", np.min(arr1))

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Mean: 30.0
Max: 50
Min: 10


In [10]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#Mathematical functions
print("Mean:", np.mean(arr2))
print("Max:", np.max(arr2))
print("Min:", np.min(arr2))

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Mean: 3.5
Max: 6
Min: 1


In [11]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#3. Array operations
print("Addition", arr1 + 5)
print("Multiplication", arr1 + 2)

#4. Mathematical functions
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))
print("Min:", np.min(arr1))

#5. Indexing and slicing
print("First element:", arr1[0])
print("Slice", arr1[1:4])

#6. Reshaping arrays
reshaped = arr1.reshape(5,1)
print("reshaped array:", reshaped)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Addition [15 25 35 45 55]
Multiplication [12 22 32 42 52]
Mean: 30.0
Max: 50
Min: 10
First element: 10
Slice [20 30 40]
reshaped array: [[10]
 [20]
 [30]
 [40]
 [50]]


In [13]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#3. Array operations
print("Addition", arr1 + 5)
print("Multiplication", arr1 + 2)

#4. Mathematical functions
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))
print("Min:", np.min(arr1))

#5. Indexing and slicing
print("First element:", arr1[0])
print("Slice", arr1[1:4])

#6. Reshaping arrays
reshaped = arr1.reshape(5,1)
print("reshaped array:", reshaped)

#7. Random numbers
random_arr = np.random.randint(1, 100, 5)

#8. Matrix multiplication
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
C = np.dot(A,B)
print("Matrix multiplication", C)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Addition [15 25 35 45 55]
Multiplication [12 22 32 42 52]
Mean: 30.0
Max: 50
Min: 10
First element: 10
Slice [20 30 40]
reshaped array: [[10]
 [20]
 [30]
 [40]
 [50]]
Matrix multiplication [[19 22]
 [43 50]]


In [1]:


                        #PANDAS


In [4]:
import pandas as pd


#1. Creating a dataset

data = {
    "Name": ["John", "Mary", "David", "Sarah", "Paul"],
    "Age": [18, 20, 19, 21, 22],
    "Score": [65, 75, 80, 72, 90]
}

df = pd.DataFrame(data)



#2. Display dataset
print("Full Dataset")
print(df)


#3. Basic information
print("\nDataset Info:")
print(df.info())

Full Dataset
    Name  Age  Score
0   John   18     65
1   Mary   20     75
2  David   19     80
3  Sarah   21     72
4   Paul   22     90

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   Score   5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None


In [1]:
print("testing")

testing


In [ ]:
#supervised Learning

In [7]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score

#Linear Regression. Example (Predicts house price)
x = np.array([[50], [60], [70], [80], [90]])
y = np.array([150, 180, 210, 240, 270])

model_lr = LinearRegression()
model_lr.fit(x,y)

predicted_price = model_lr.predict([[75]])
print("Predicted price for 75 sq.m:", predicted_price[-1])

Predicted price for 75 sq.m: 225.0


In [17]:
arr1 = np.max(np.array([10,20,30,40,50]))
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr1)
# print(arr1.size)
# print(arr2.shape)
# print(arr2.size)

50


In [58]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

data = {
    "Age": [18, 20, np.nan, 22, 21],
    "Gender": ["Male", "Female", "Female", "Male", "Male"],
    "Score": [65, 75, 80, np.nan, 90],
    "Passed": ["No", "Yes", "Yes", "Yes", "Yes"]
}

df = pd.DataFrame(data)

df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

print(df)

# Encoding categorical data
encoder = LabelEncoder()
df["Gender"] = encoder.fit_transform(df["Gender"])
df["Passed"] = encoder.fit_transform(df["Passed"])

print(df)

scaler = StandardScaler()
df[["Age", "ExamScore"]] = scaler.fit_transform([["Age", "ExamScore"]])

print("\n\nafter Handling Missing Values")
print(df)

C:\Users\DELL\AppData\Local\Temp\ipykernel_9708\2942170855.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_9708\2942170855.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For examp

     Age  Gender  Score Passed
0  18.00    Male   65.0     No
1  20.00  Female   75.0    Yes
2  20.25  Female   80.0    Yes
3  22.00    Male   77.5    Yes
4  21.00    Male   90.0    Yes
     Age  Gender  Score  Passed
0  18.00       1   65.0       0
1  20.00       0   75.0       1
2  20.25       0   80.0       1
3  22.00       1   77.5       1
4  21.00       1   90.0       1


ValueError: could not convert string to float: 'Age'

In [59]:
08031223562

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (2364269109.py, line 1)

In [60]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

data = {
    "Age": [18, 20, np.nan, 22, 21],
    "Gender": ["Male", "Female", "Female", "Male", "Male"],
    "Score": [65, 75, 80, np.nan, 90],
    "Passed": ["No", "Yes", "Yes", "Yes", "Yes"]
}

df = pd.DataFrame(data)

# Handle missing values
df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

print("Before Encoding:\n", df)

# Encoding categorical data
gender_encoder = LabelEncoder()
df["Gender"] = gender_encoder.fit_transform(df["Gender"])

passed_encoder = LabelEncoder()
df["Passed"] = passed_encoder.fit_transform(df["Passed"])

print("\nAfter Encoding:\n", df)

# Scaling numeric columns
scaler = StandardScaler()
df[["Age", "Score"]] = scaler.fit_transform(df[["Age", "Score"]])

print("\nAfter Scaling:\n", df)






Before Encoding:
      Age  Gender  Score Passed
0  18.00    Male   65.0     No
1  20.00  Female   75.0    Yes
2  20.25  Female   80.0    Yes
3  22.00    Male   77.5    Yes
4  21.00    Male   90.0    Yes

After Encoding:
      Age  Gender  Score  Passed
0  18.00       1   65.0       0
1  20.00       0   75.0       1
2  20.25       0   80.0       1
3  22.00       1   77.5       1
4  21.00       1   90.0       1

After Scaling:
         Age  Gender     Score  Passed
0 -1.700840       1 -1.550434       0
1 -0.188982       0 -0.310087       1
2  0.000000       0  0.310087       1
3  1.322876       1  0.000000       1
4  0.566947       1  1.550434       1


C:\Users\DELL\AppData\Local\Temp\ipykernel_9708\1138408087.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_9708\1138408087.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For examp

In [61]:
# SUPERVISED MACHINE LEARNING ( LINEAR AND LOGISTIC REGRESSION)

In [14]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score

# Linear Regression Example (Predicting the house price)
x = np.array([[50], [60], [70], [80], [90]]) #square meters
y = np.array([150, 180, 210, 240, 270])

model_lr = LinearRegression()
model_lr.fit(x,y)

predicted_price = model_lr.predict([[75]])
# print(predicted_price[0])


# Logistic Regression Example( Predict pass/fail)
data = {
    "Hours_Studied": [1,2,3,4,5,6],
    "Passed": [0,0,0,1,1,1] 
}

df = pd.DataFrame(data)
x_log = df[["Hours_Studied"]]
y_log = df[["Passed"]]

model_log = LogisticRegression()
model_log.fit(x_log, y_log)

# Predicting if a student passes after studing for 3.5 hours
predicted_result = model_log.predict([[3.5]])

print(predicted_result)
print("Predicted result for 3.5 hours:", "Pass" if predicted_result[0] == 1 else "fail")


# Evaluating the models
y_pred_lr = model_lr.predict(x)
mse = mean_squared_error(y, y_pred_lr)
# print(y_pred_lr)
print("Linear Regression Mean Squared Error:", mse)

y_pred_log = model_log.predict(x_log)
accuracy = accuracy_score(y_log, y_pred_log)
print("Logistic Regression Accuracy: ", accuracy)

[1]
Predicted result for 3.5 hours: Pass
Linear Regression Mean Squared Error: 0.0
Logistic Regression Accuracy:  1.0


C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
# LOGISTIC REGRESSION EXAMPLE()