In [1]:
Print("hello")

NameError: name 'Print' is not defined

In [2]:
print("hello")


hello


In [3]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6


In [6]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr1", arr1.shape)
print("Size of arr2", arr2.size)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr1 (5,)
Size of arr2 6


In [7]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)


iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6


In [8]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#3. Array operations
print("Addition", arr1 + 5)
print("Multiplication", arr1 + 2)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Addition [15 25 35 45 55]
Multiplication [12 22 32 42 52]


In [9]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#Mathematical functions
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))
print("Min:", np.min(arr1))

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Mean: 30.0
Max: 50
Min: 10


In [10]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#Mathematical functions
print("Mean:", np.mean(arr2))
print("Max:", np.max(arr2))
print("Min:", np.min(arr2))

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Mean: 3.5
Max: 6
Min: 1


In [11]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#3. Array operations
print("Addition", arr1 + 5)
print("Multiplication", arr1 + 2)

#4. Mathematical functions
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))
print("Min:", np.min(arr1))

#5. Indexing and slicing
print("First element:", arr1[0])
print("Slice", arr1[1:4])

#6. Reshaping arrays
reshaped = arr1.reshape(5,1)
print("reshaped array:", reshaped)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Addition [15 25 35 45 55]
Multiplication [12 22 32 42 52]
Mean: 30.0
Max: 50
Min: 10
First element: 10
Slice [20 30 40]
reshaped array: [[10]
 [20]
 [30]
 [40]
 [50]]


In [13]:
import numpy as np

#1. Creating arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print("iD Array", arr1)
print("2D Array: \n", arr2)

#2. Shape and size
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)

#3. Array operations
print("Addition", arr1 + 5)
print("Multiplication", arr1 + 2)

#4. Mathematical functions
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))
print("Min:", np.min(arr1))

#5. Indexing and slicing
print("First element:", arr1[0])
print("Slice", arr1[1:4])

#6. Reshaping arrays
reshaped = arr1.reshape(5,1)
print("reshaped array:", reshaped)

#7. Random numbers
random_arr = np.random.randint(1, 100, 5)

#8. Matrix multiplication
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
C = np.dot(A,B)
print("Matrix multiplication", C)

iD Array [10 20 30 40 50]
2D Array: 
 [[1 2 3]
 [4 5 6]]
Shape of arr2 (2, 3)
Size of arr2 6
Addition [15 25 35 45 55]
Multiplication [12 22 32 42 52]
Mean: 30.0
Max: 50
Min: 10
First element: 10
Slice [20 30 40]
reshaped array: [[10]
 [20]
 [30]
 [40]
 [50]]
Matrix multiplication [[19 22]
 [43 50]]


In [1]:


                        #PANDAS


In [4]:
import pandas as pd


#1. Creating a dataset

data = {
    "Name": ["John", "Mary", "David", "Sarah", "Paul"],
    "Age": [18, 20, 19, 21, 22],
    "Score": [65, 75, 80, 72, 90]
}

df = pd.DataFrame(data)



#2. Display dataset
print("Full Dataset")
print(df)


#3. Basic information
print("\nDataset Info:")
print(df.info())

Full Dataset
    Name  Age  Score
0   John   18     65
1   Mary   20     75
2  David   19     80
3  Sarah   21     72
4   Paul   22     90

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   Score   5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None


In [1]:
print("testing")

testing


In [ ]:
#supervised Learning

In [5]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score

#Linear Regression. Example (Predicts house price)
x = np.array([[50], [60], [70], [80], [90]])
y = np.array([150, 180, 210, 240, 270])

model_lr = LinearRegression()
model_lr.fit(x,y)

predicted_price = model_lr.predict([[75]])
print("Predicted price for 75 sq.m:", predicted_price[0])

Predicted price for 75 sq.m: 225.0
